In [1]:
import numpy as np
import pandas as pd
import mlp
import sklearn.model_selection
import importlib
import time

In [11]:
data = pd.read_csv("../../mnist_train.csv")

In [123]:
importlib.reload(mlp)

<module 'mlp' from '/home/adrien/Documents/IFT6135/assigment1/practical/mlp.py'>

In [4]:
data.values.shape

(60000, 785)

In [86]:
X = data.values[:100,1:]
Y = data.values[:100,0]

In [75]:
X_train, X_test, Y_train, Y_test = \
            sklearn.model_selection.train_test_split( X, Y, \
                            test_size=0.33, random_state=42)

In [124]:
model1 = mlp.MLP(784, 500, 500, 10, init="normal", activation="sigmoid")

Input dimension 784	Layer 1 dimension 500	Layer 2 dimension 500	Output dimension 10
Total number of parameters : 648010


In [125]:
model1.train(X_train, Y_train, 5, 1, 1e-07)

Epoch 1/5	Examples 670/670	Accuracy 0.113	Epoch time 11.88s	Training time 11.88s
Epoch 2/5	Examples 670/670	Accuracy 0.116	Epoch time 11.87s	Training time 23.75s
Epoch 3/5	Examples 670/670	Accuracy 0.116	Epoch time 7.64s	Training time 31.39s
Epoch 4/5	Examples 670/670	Accuracy 0.116	Epoch time 7.01s	Training time 38.40s
Epoch 5/5	Examples 670/670	Accuracy 0.116	Epoch time 7.67s	Training time 46.07s
Total training time 46.07s


In [110]:
model1.evaluate(X_test, Y_test)

0.07575757575757576

In [105]:
model1.predict(X_train)

array([7, 6, 3, 3, 5, 5, 4, 6, 0, 8, 2, 5, 9, 8, 1, 5, 1, 0, 6, 9, 3, 5,
       3, 0, 3, 4, 5, 9, 0, 8, 9, 7, 3, 1, 4, 7, 7, 7, 6, 6, 0, 8, 7, 8,
       1, 0, 7, 6, 5, 2, 6, 5, 8, 0, 2, 8, 7, 5, 4, 2, 7, 8, 2, 0, 1, 0,
       3, 4, 5, 0, 1, 7, 8, 4, 1, 5, 4, 4, 0, 1, 5, 1, 0, 4, 5, 1, 4, 5,
       7, 1, 6, 3, 7, 2, 3, 6, 6, 1, 1, 4, 9, 2, 4, 8, 5, 3, 5, 1, 6, 9,
       7, 1, 4, 5, 8, 0, 0, 9, 4, 2, 4, 2, 8, 4, 1, 7, 8, 0, 2, 4, 3, 1,
       6, 1, 2, 1, 0, 5, 9, 2, 9, 4, 7, 4, 4, 4, 5, 4, 4, 1, 1, 8, 5, 5,
       1, 9, 7, 4, 9, 7, 8, 6, 5, 5, 7, 2, 1, 1, 9, 4, 4, 1, 6, 7, 9, 5,
       2, 9, 5, 5, 4, 1, 5, 7, 7, 8, 4, 3, 3, 4, 3, 0, 3, 4, 6, 2, 1, 3,
       5, 6, 1, 0, 5, 5, 2, 4, 9, 0, 7, 0, 9, 4, 5, 9, 2, 0, 5, 0, 2, 6,
       9, 0, 2, 9, 3, 5, 4, 7, 9, 7, 9, 6, 4, 8, 7, 1, 3, 9, 3, 3, 3, 1,
       7, 3, 7, 0, 4, 1, 0, 5, 0, 5, 1, 0, 3, 5, 5, 5, 4, 5, 8, 4, 0, 4,
       3, 7, 5, 8, 4, 0, 1, 4, 3, 3, 2, 3, 2, 4, 4, 4, 7, 7, 6, 0, 7, 1,
       0, 6, 0, 9, 3, 3, 4, 2, 3, 7, 5, 7, 9, 2, 0,

In [119]:
func = mlp.Tanh()

In [114]:
func.derivative(np.array([-1,0,1]))

array([0.19661193, 0.25      , 0.19661193])

In [117]:
a = np.array([-1,0,1])

In [122]:
func.derivative(a)

array([0.41997434, 1.        , 0.41997434])